export const COACH_LIST_REQUEST = 'COACH_LIST_REQUEST';
export const COACH_LIST_SUCCESS = 'COACH_LIST_SUCCESS';
export const COACH_LIST_FAILURE = 'COACH_LIST_FAILURE';

export const COACH_DETAILS_REQUEST = 'COACH_DETAILS_REQUEST';
export const COACH_DETAILS_SUCCESS = 'COACH_DETAILS_SUCCESS';
export const COACH_DETAILS_FAILURE = 'COACH_DETAILS_FAILURE';

export const COACH_DELETE_REQUEST = 'COACH_DELETE_REQUEST';
export const COACH_DELETE_SUCCESS = 'COACH_DELETE_SUCCESS';
export const COACH_DELETE_FAILURE = 'COACH_DELETE_FAILURE';

export const COACH_CREATE_REQUEST = 'COACH_CREATE_REQUEST';
export const COACH_CREATE_SUCCESS = 'COACH_CREATE_SUCCESS';
export const COACH_CREATE_FAILURE = 'COACH_CREATE_FAILURE';
export const COACH_CREATE_RESET = 'COACH_CREATE_RESET';

export const COACH_UPDATE_REQUEST = 'COACH_UPDATE_REQUEST';
export const COACH_UPDATE_SUCCESS = 'COACH_UPDATE_SUCCESS';
export const COACH_UPDATE_FAILURE = 'COACH_UPDATE_FAILURE';
export const COACH_UPDATE_RESET = 'COACH_UPDATE_RESET';

export const COACH_CREATE_REVIEW_REQUEST = 'COACH_CREATE_REVIEW_REQUEST';
export const COACH_CREATE_REVIEW_SUCCESS = 'COACH_CREATE_REVIEW_SUCCESS';
export const COACH_CREATE_REVIEW_FAILURE = 'COACH_CREATE_REVIEW_FAILURE';
export const COACH_CREATE_REVIEW_RESET = 'COACH_CREATE_REVIEW_RESET';

export const COACH_TOP_RATED_REQUEST = 'COACH_TOP_RATED_REQUEST';
export const COACH_TOP_RATED_SUCCESS = 'COACH_TOP_RATED_SUCCESS';
export const COACH_TOP_RATED_FAILURE = 'COACH_TOP_RATED_FAILURE';
